language: python
python:
  - "3.7"
env:
  - DJANGO=3.0.5 DB=sqlite3
before_install:
  - export DJANGO_SETTINGS_MODULE=DS.settings
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
  - coverage run manage.py test
after_success:
  - coverage report
  - coveralls